AtomsBase support
Chemellia/AtomGraphs.jl pull request #9
Opened 2023-01-12 22:23 UTC by rkurchin

Adds support for building graphs from AtomsBase systems. See commit message for more details...

2023-01-13 19:12 UTC, rkurchin commented
@thazhemadam, didn't we see this GLIBCXX thing before with another Python dependency somewhere? I can't recall what the fix was...

2023-01-16 17:10 UTC, rkurchin commented
I was wondering if switching over to PythonCall might help any of these issues (I've heard it's better than PyCall, also that it doesn't play well with PyCall which is presumably related to why I couldn't get AtomsIO.jl to play nice with this, which I was also hoping to use for reading/writing files), but am having trouble getting that working either. If you want to take a peek, check out the `pythoncall` branch I just pushed...

2023-01-17 13:26 UTC, thazhemadam requested changes
Mostly looks good to me. Just a couple of suggestions. 🙂

2023-01-17 13:26 UTC, thazhemadam commented on Project.toml
>  [compat]
We should add compats for `AtomsBase`, `StaticArrays` and `Unitful`

2023-01-17 13:26 UTC, thazhemadam commented on src/graph_building.jl
> +    sys;
```suggestion
    sys::Union{Crystal, AtomsBase.AbstractSystem};
```

2023-01-17 13:26 UTC, thazhemadam commented on src/graph_building.jl
> +function neighbor_list(sys; cutoff_radius::Real = 8.0)
```suggestion
function neighbor_list(sys::Union{Crystal, AtomsBase.AbstractSystem}; cutoff_radius::Real = 8.0)
```

2023-01-17 13:27 UTC, thazhemadam commented
> @thazhemadam, didn't we see this GLIBCXX thing before with another Python dependency somewhere? I can't recall what the fix was...

Yeah, I vaguely recall seeing this too. I think using `deps.jl` helped fix the issue? Not entirely sure.

2023-01-17 13:32 UTC, thazhemadam commented
>  I was wondering if switching over to PythonCall might help any of these issues (I've heard it's better than PyCall, also that it doesn't play well with PyCall which is presumably related to why I couldn't get AtomsIO.jl to play nice with this, which I was also hoping to use for reading/writing files), but am having trouble getting that working either. If you want to take a peek, check out the pythoncall branch I just pushed...


PythonCall _might_ help with these issues, but it will also start making trouble any time you try to use sysimages with the packages, which is why I'm wary of it. [^1] I also have a branch which has `PythonCall` + `CondaPkg` set up - [`at/condapkg`](https://github.com/Chemellia/AtomGraphs.jl/tree/at/condapkg). 😆
I didn't open a PR since I imagine being unable to package this is a bit of a deal breaker.

[^1]: https://github.com/cjdoris/PythonCall.jl/issues/129

2023-01-30 12:54 UTC, rkurchin commented
Cherry-picking this over to #10, closing...

2023-01-30 12:54 UTC, closed without merging